export const inputTypes = {
  TEXT: 'INPUT_TYPE_TEXT',
  NUMBER: 'INPUT_TYPE_NUMBER',
  EMAIL: 'INPUT_TYPE_EMAIL',
  CHECKBOX: 'INPUT_TYPE_CHECKBOX',
  PHONE: 'INPUT_TYPE_PHONE',
  SELECT: 'INPUT_TYPE_SELECT',
  MULTISELECT: 'INPUT_TYPE_MULTISELECT',
  TREESELECT: 'INPUT_TYPE_TREESELECT',
  DATE: 'INPUT_TYPE_DATE',
  DATERANGE: 'INPUT_TYPE_DATERANGE'
}
